/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type User = {
  /*
   * ユーザID
   */
  id: number;
  /*
   * ユーザ名
   */
  name: string;
  /*
   * 年齢
   */
  age: number | null;
  /*
   * 有効フラグ
   */
  is_enabled: boolean;
};

export type RegisterUser = {
  /*
   * ユーザ名
   */
  name: string;
  /*
   * 年齢
   */
  age: number | null;
  /*
   * 有効フラグ
   */
  is_enabled?: boolean;
};

export type Success = {
  /*
   * @format int32
   * @example 200
   */
  statusCode?: number;
};

export type Error = {
  /*
   * @format int32
   * @example 400
   */
  statusCode?: number;
};

export type Unauthorized = {
  /*
   * @format int32
   * @example 401
   */
  statusCode?: number;
};
